// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/sdivyansh59/digantara-backend-golang-assignment/app/greeting"
	"github.com/sdivyansh59/digantara-backend-golang-assignment/app/internal-lib/utils"
	"github.com/sdivyansh59/digantara-backend-golang-assignment/app/setup"
)

// Injectors from wire.go:

// InitializeApp wires up all dependencies and returns the application/service instance
func InitializeApp() (*App, error) {
	mux := setup.ProvideSingletonChiRouter()
	api := setup.ProvideSingletonHuma(mux)
	defaultConfig := utils.ProvideDefaultConfig()
	controller := greeting.NewController()
	controllers := setup.ProvideControllers(controller)
	app := newApp(mux, api, defaultConfig, controllers)
	return app, nil
}
